name: dragones_templarios_app
version: 1.0.0+1

environment:
  sdk: '^3.7.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
flutter:
  assets:
    - assets/logo.png

